version: '3'
services:
  jenkins:
    container_name: jenkins-docker
    image: jenkins-docker:v1.2
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
networks:
  net:








